# Generated by Django 4.1.3 on 2022-11-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carType', models.CharField(max_length=100)),
                ('AreaLooking', models.CharField(choices=[('Front', 'Front'), ('Behind', 'Behind'), ('Left', 'Left'), ('Right', 'Right')], max_length=100)),
                ('FlexSensorBend', models.PositiveIntegerField()),
            ],
        ),
    ]
