# Generated by Django 4.1.3 on 2022-11-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcrash',
            name='Speed',
            field=models.PositiveIntegerField(default=120),
            preserve_default=False,
        ),
    ]
