# Generated by Django 4.1.3 on 2022-11-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_carcrash_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCrashRandom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('TypeOfCar', models.CharField(max_length=100)),
                ('TypeOfCrash', models.CharField(max_length=100)),
                ('Damage', models.CharField(max_length=100)),
                ('DriverSight', models.CharField(max_length=100)),
                ('FlexSensorReading', models.PositiveIntegerField()),
                ('Speed', models.PositiveIntegerField()),
            ],
        ),
    ]
