# Generated by Django 4.1.3 on 2022-11-15 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_carcrashrandom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Damage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DriverSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DriverSight', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FirstName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LastName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeOfCar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeOfCrash', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='carcrashrandom',
            name='Damage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.damage'),
        ),
        migrations.AlterField(
            model_name='carcrashrandom',
            name='DriverSight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.driversight'),
        ),
        migrations.AlterField(
            model_name='carcrashrandom',
            name='FirstName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.firstname'),
        ),
        migrations.AlterField(
            model_name='carcrashrandom',
            name='Surname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lastname'),
        ),
        migrations.AlterField(
            model_name='carcrashrandom',
            name='TypeOfCar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.typeofcar'),
        ),
        migrations.AlterField(
            model_name='carcrashrandom',
            name='TypeOfCrash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.typeofcrash'),
        ),
    ]
